# Generated by Django 5.0.6 on 2024-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
