# Generated by Django 5.0.6 on 2024-08-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0002_rename_index_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='index',
        ),
    ]
