# Generated by Django 5.0.6 on 2024-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0003_rename_blog_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='index',
            new_name='Blog',
        ),
    ]
