# Generated by Django 5.0.6 on 2024-08-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0004_contact_rename_index_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='Subject',
        ),
    ]
