# Generated by Django 5.0.6 on 2024-08-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0005_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(),
        ),
    ]
