# Generated by Django 5.0.6 on 2024-08-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0006_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
