# Generated by Django 5.0.6 on 2024-09-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0007_postblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postblog',
        ),
    ]
