# Generated by Django 5.0.6 on 2024-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0008_delete_postblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
